apiVersion: v2

name: universal-app

description: Reusable Helm Chart for AWS EKS Applications

type: application

version: 1.0.1

appVersion: "1.0.1"

keywords:
  - eks
  - kubernetes
  - helm
  - aws
  - deployment

maintainers:
  - name: Yousaf Hamza