{{- if .Values.secret.enabled }}

apiVersion: v1
kind: Secret

metadata:
  name: {{ include "universal-app.fullname" . }}-secret

type: Opaque

stringData:
{{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}

{{- end }}